### ISSUE TITLE
Generator 'StronglyGenerator' failed to generate source.

### ISSUE THREAD

**Issue by yoi102** [lucasteles/Strongly#3]
1>CSC : warning CS8785: Generator 'StronglyGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Sequence contains no elements'
    
It didn't work properly when I use version 1.2.0 or higher

![image](https://github.com/lucasteles/Strongly/assets/77535233/4bdc5b33-0607-4f55-9003-081a4d5d5f0e)
  
![image](https://github.com/lucasteles/Strongly/assets/77535233/df697dbf-93cc-4ce2-870b-df8c05586241)

**Comment by ignatandrei** [comment]
Also do not see that works with 1.4.1
See attached file
[src.zip](https://github.com/lucasteles/Strongly/files/12267598/src.zip)

**Comment by ignatandrei** [comment]
I use version 1.1 for the example with RSCG at https://ignatandrei.github.io/RSCG_Examples/v2/docs/Strongly

**Comment by lucasteles** [comment]
@ignatandrei @yoi102 This error was occurring only when the global default values aren't defined

fixed in https://github.com/lucasteles/Strongly/releases/tag/1.4.2

**Comment by ignatandrei** [comment]
https://ignatandrei.github.io/RSCG_Examples/v2/docs/Strongly
